# Generated by Django 4.0.6 on 2022-07-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_nota_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
