# Generated by Django 4.0.6 on 2022-07-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_usuario_id_nota_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='titulo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
