# Generated by Django 4.0.6 on 2022-07-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_nota_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='titulo',
            field=models.CharField(blank=True, default=' ', max_length=128, null=True),
        ),
    ]
