# Generated by Django 4.0.6 on 2022-07-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_nota_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='senha',
        ),
    ]
